"""Joins plan/<AREA>.md into TEST_PLAN.md with a summary and the menu-command coverage matrix."""
import sys
from collections import Counter
from planlib import ROOT, all_cases, commands, coverage, parse, plan_files

cases, errors = all_cases()
cov = coverage(cases)
missing = [c for c in commands() if not cov[c["id"]]]
out = ["# NotepadMac — end-to-end test plan", "",
       "Generated by `tools/build_plan.py` from `plan/*.md`; edit those, not this file.",
       "How the tests drive the application: `HARNESS.md`.", "",
       "## Summary", "", "| Area | Cases |", "|---|---:|"]
per = Counter(c["area"] for c in cases)
for p in plan_files():
    title, cs, _ = parse(p)
    out.append(f"| [{title}](#{p.stem.lower()}) | {len(cs)} |")
out += [f"| **Total** | **{len(cases)}** |", "",
        f"Menu commands covered: {len(commands()) - len(missing)} of {len(commands())}.", ""]
for p in plan_files():
    body = p.read_text().strip().splitlines()
    out += [f'<a id="{p.stem.lower()}"></a>', ""] + ["#" + l if l.startswith("#") else l for l in body] + [""]
out += ["## Appendix: menu command coverage", "", "| Menu | Command | Id | Cases |", "|---|---|---|---|"]
for c in commands():
    out.append(f"| {c['menu']} | {c['label']} | `{c['id']}` | {', '.join(cov[c['id']][:6]) or '**none**'} |")
(ROOT / "TEST_PLAN.md").write_text("\n".join(out) + "\n")
print(f"{len(cases)} cases; {len(missing)} uncovered commands; {len(errors)} format errors")
for e in errors[:50]:
    print("  ", e)
for m in missing[:80]:
    print("   uncovered:", m["menu"], m["id"], m["label"])
sys.exit(1 if errors else 0)
